export const REQUEST_SPENDINGS_PENDING = 'REQUEST_SPENDINGS_PENDING';
export const REQUEST_SPENDINGS_SUCCESS = 'REQUEST_SPENDINGS_SUCCESS';
export const REQUEST_SPENDINGS_ERROR = 'REQUEST_SPENDINGS_ERROR';
export const DELETE_SPENDING_PENDING = 'DELETE_SPENDING_PENDING';
export const DELETE_SPENDING_SUCCESS = 'DELETE_SPENDING_SUCCESS';
export const DELETE_SPENDING_ERROR = 'DELETE_SPENDING_ERROR';
<<<<<<< HEAD
export const POST_SPENDING_PENDING = 'POST_SPENDING_PENDING ';
export const POST_SPENDING_SUCCESS = 'POST_SPENDING_SUCCESS';
export const POST_SPENDING_ERROR = 'POST_SPENDING_ERROR';
export const UPDATE_SPENDING_PENDING = 'UPDATE_SPENDING_PENDING';
export const UPDATE_SPENDING_SUCCESS = 'UPDATE_SPENDING_SUCCESS';
export const UPDATE_SPENDING_ERROR = 'UPDATE_SPENDING_ERROR';
=======
export const REQUEST_ALL_SPENDINGS_PENDING = 'REQUEST_ALL_SPENDINGS_PENDING';
export const REQUEST_ALL_SPENDINGS_SUCCESS = 'REQUEST_ALL_SPENDINGS_SUCCESS';
export const REQUEST_ALL_SPENDINGS_ERROR = 'REQUEST_ALL_SPENDINGS_ERROR';
>>>>>>> 3a84c88 (feature: Create Chart)
