export const REQUEST_SPENDINGS_PENDING = 'REQUEST_SPENDINGS_PENDING';
export const REQUEST_SPENDINGS_SUCCESS = 'REQUEST_SPENDINGS_SUCCESS';
export const REQUEST_SPENDINGS_ERROR = 'REQUEST_SPENDINGS_ERROR';
